# Generated by Django 5.1.7 on 2025-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doador', models.CharField(max_length=100)),
                ('email_doador', models.EmailField(max_length=254)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
